sudo: false
language: node_js
node_js:
  - "8"
script:
  - npm run lint
  - npm test
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: dist/static
  on:
    branch: gh-pages